# Generated by Django 3.1.6 on 2021-02-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRecord',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CityRecord',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('pincode', models.IntegerField(default=None, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapiauthapp.countryrecord')),
            ],
        ),
    ]
