# Generated by Django 3.1.6 on 2021-02-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapiauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityrecord',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='basicapiauthapp.countryrecord'),
        ),
        migrations.AlterField(
            model_name='cityrecord',
            name='pincode',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
